plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.147' apply false
    id 'net.darkhax.curseforgegradle' version '1.1.27' apply false
    id 'com.modrinth.minotaur' version '2.+' apply false
}

tasks.register('publishMod') {
    group = 'publishing'
    description = 'Publishes the Fabric and NeoForge builds to CurseForge and Modrinth.'
    dependsOn(
            ':fabric:publishCurseForge',
            ':fabric:modrinth',
            ':neoforge:publishCurseForge',
            ':neoforge:modrinth'
    )
}
