# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.14.2
group=com.nemonotfound.nemos.woodcutter
java_version=25

# Common
minecraft_version=26.3
mod_name=Nemo's Woodcutter
mod_author=Nemo
mod_id=nemos_woodcutter
mod_id_jar=nemos-woodcutter
license=MIT
credits=Nemo
description=The Woodcutter is just like the Stonecutter. Just for wood!
minecraft_version_range=[26.3]
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.3-1

# Fabric
fabric_version=0.161.0+26.3
fabric_loader_version=0.19.5

# NeoForge
neoforge_version=26.3.0.16-beta
neoforge_loader_version_range=[11,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
biomes_o_plenty_version=26.3.0.0.6
glitchcore_version=26.3.0.0.3
terrablender_version=26.3.0.0.7
nemos_mossy_blocks_version=26.3-2.4
nemos_vertical_slabs_version=26.3-2.3.5

# Upload
curseforge_project_id=914549
modrinth_project_id=nemos-woodcutter
